name: PSNR_16x_inference
suffix: _full  # add suffix to saved images
model: sr
distortion: sr
scale: 16
crop_border: ~  # crop border when evaluation. If None(~), crop the scale pixels
gpu_ids: [0]

datasets:
  inference:  # the inference dataset
    name: 8K_test
    mode: LQ
    dataroot_LQ: /media/andreis/storage/datasets/8K/testLR
    batch_size: 1
    phase: inference

#### network structures
network_G:
  which_model_G: RRDBNet_16x
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 16
  upscale: 16

#### path
path:
  pretrain_model_G: /home/andreis/workspace/mmsr/experiments/002_PSNR_base_model_feature_loss_16_progressive/models/200000_G.pth
