#### general settings
name: 002_PSNR_mask_no_align_corners
use_tb_logger: true
model: sr
distortion: sr
scale: 16
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGT
    dataroot_GT: /home/andreis/Datasets/DIV8K/train_lmdb/DIV8K_sub.lmdb
    dataroot_LQ: /home/andreis/Datasets/DIV8K/train_lmdb/DIV8K_sub_bicLRx16.lmdb

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 32
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: DIV2K
    mode: LQGT
    dataroot_GT: /media/andreis/storage/datasets/8K/validationHR_2048_subset/HR/x16
    dataroot_LQ: /media/andreis/storage/datasets/8K/validationHR_2048_subset/LR/x16

#### network structures
network_G:
  which_model_G: RRDBNet_16x
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 16
  upscale: 16

#### path
path:
  pretrain_model_G: /home/andreis/workspace/mmsr/experiments/pretrained_models/RRDB_PSNR_16x_25.031.pth
  strict_load: false
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 200000
  warmup_iter: -1  # no warm up
  T_period: [50000, 50000, 50000, 50000]
  restarts: [50000, 100000, 150000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 10.0
  feature_criterion: l1
  feature_weight: 1.0
  mask_criterion: l1
  mask_weight: 10.0

  manual_seed: 10
  val_freq: 5000.0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
